### ISSUE TITLE
Libre license for Libre elections

### ISSUE THREAD

**Issue by viniciusmuller** [pauloo27/votacao#1]
hey man I need to run elections in my country and this license does not seem Libre enough, how can we fix it?!?!

**Comment by pauloo27** [comment]
what country AGPL is not "libre enough"???? Ancapstão???

![get some help](https://media1.tenor.com/m/LLZKjI9vcFMAAAAC/michael-jordan-get-some-help.gif)

And I don't wanna see anyone doing `if voto22 { voto13 = confirma }` on here. AGPL stays.

Thanks.
